services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: soc_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: soc_logs
    ports:
      - "5435:5432"  # <--- CHANGE THIS TO 5435
    volumes:
      - soc_pg_data:/var/lib/postgresql/data

volumes:
  soc_pg_data: